config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :list_items
  resources :lists

  unauthenticated do
   root :to => 'lists#index', as: :unauthenticated_root
 end

  authenticated do
    root :to => 'tasks#not_completed', as: :authenticated_root
  end

  resources :tasks do
    collection do
      get 'completed'
      get 'not_completed'
    end
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  validates :name, presence: true

  has_many :list_items

  accepts_nested_attributes_for :list_items, reject_if: lambda {|attributes| attributes['description'].blank?}, allow_destroy: true

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  
  belongs_to :list
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user

  audited

  def self.completed
    all.select { |task| task.completed }
  end

  def self.not_completed
    all.select { |task| !task.completed }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render :show, status: :created, location: @list_item }
      else
        format.html { render :new }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_item }
      else
        format.html { render :edit }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_items_url, notice: 'List item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:id, :description, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
    @list.list_items.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:id, :name, list_items_attributes: [:id, :description, :_destroy])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.all
  end

  def completed
    @tasks = current_user.tasks.completed
  end

  def not_completed
    @tasks = current_user.tasks.not_completed
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    create_update(@task.save, 'created', new)
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    create_update(@task.update(task_params),'updated', edit)
  end

  def create_update(call, string, rendering)

    respond_to do |format|
      if call
        format.html { redirect_to tasks_path, notice: "Task was successfully #{string}." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :rendering }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Todo
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags
  %body
    %ul
    - if user_signed_in?
      %li{:style => "display: inline-block; margin:1rem "}
        = link_to "Incomplete Tasks", not_completed_tasks_path
        %li{:style => "display: inline-block; margin:1rem "}
          = link_to "Completed Tasks", completed_tasks_path
          %li{:style => "display: inline-block; margin:1rem"}
            = link_to "All Tasks", tasks_url
            %li{:style => "display: inline-block; margin:1rem"}
              = link_to "Lists", lists_url
              %li{:style => "display: inline-block; margin:1rem"}
                = link_to('Logout', destroy_user_session_path, method: :delete)
    - else
      %li{:style => "display: inline-block; margin:1rem"}
        = link_to "Lists", lists_url
        %li{:style => "display: inline-block; margin:1rem"}
          = link_to('Login', new_user_session_path)
    =yield

app/views/list_items/_form.html.haml
= form_for @list_item do |f|
  - if @list_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list_item.errors.count, "error")} prohibited this list_item from being saved:"
      %ul
        - @list_item.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/list_items/edit.html.haml
%h1 Editing list_item

= render 'form'

= link_to 'Show', @list_item
\|
= link_to 'Back', list_items_path

app/views/list_items/index.html.haml
%h1 Listing list_items

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @list_items.each do |list_item|
      %tr
        %td= link_to 'Show', list_item
        %td= link_to 'Edit', edit_list_item_path(list_item)
        %td= link_to 'Destroy', list_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New List item', new_list_item_path

app/views/list_items/new.html.haml
%h1 New list_item

= render 'form'

= link_to 'Back', list_items_path

app/views/list_items/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_list_item_path(@list_item)
\|
= link_to 'Back', list_items_path

app/views/lists/_form.html.haml
= form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  %h3= f.label "List Name"
  = f.text_field :name
  %ul
  =f.nested_fields_for :list_items do |list_item|
    %li
      =list_item.label  "Item"
      = list_item.text_field :description, :required => true
      = list_item.remove_nested_fields_link
  = f.add_nested_fields_link :list_items do
    %button New item
  .actions
    = f.submit 'Save'

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
%h1 Lists
%p#notice= notice

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @lists.each do |list|
      %tr
        %td
          %h3=  list.name
        %td= link_to 'Show', list
        %td= link_to 'Edit', edit_list_path(list)
        %td= link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New List', new_list_path

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.haml
%p#notice= notice
%h2= @list.name
- @list.list_items.each do |item|
  %ul
    %li= item.description

= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path

app/views/tasks/_form.html.haml
=form_for @task do |f|
  -if @task.errors.any?
    #error_explanation
      %h2="#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        -@task.errors.full_messages.each do |msg|
          %li= msg

  .field
    =f.label :name
    =f.text_field :name
  - if @task.id.present?
    .field
      =f.label :completed
      =f.check_box :completed
  .actions
    =f.submit 'Save'

app/views/tasks/completed.html.haml
%h1 Completed Tasks

%table
  %thead
    %tr
      %th{:style => "text-align:left"} Name
      %th Completed

  %tbody
    - @tasks.each do |task|
      %tr
        %td
          %b= task.name
        %td=task.completed
        %td=link_to 'Show', task
        %td=link_to 'Edit', edit_task_path(task)
        %td=link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %tr
        %td
          %ul
            %p
              %b Task History:
              - task.audits.each do |audit|
                %li= audit.audited_changes

%br

app/views/tasks/edit.html.haml
%h1 Editing task

=render 'form'

=link_to 'Show', @task
\|
=link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Tasks
%p#notice= notice

%table
  %thead
    %tr
      %th Name
      %th Completed
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td=task.name
        %td=task.completed
        %td=link_to 'Show', task
        %td=link_to 'Edit', edit_task_path(task)
        %td=link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

=link_to 'Add a task', new_task_path

app/views/tasks/new.html.haml
%h1 Create a task

=render 'form'

=link_to 'Back', tasks_path

app/views/tasks/not_completed.html.haml
%h1 Not Completed Tasks

%table
  %thead
    %tr
      %th Name
      %th Completed
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td=task.name
        %td=task.completed
        %td=link_to 'Show', task
        %td=link_to 'Edit', edit_task_path(task)
        %td=link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/tasks/show.html.haml
%p#notice=notice

%p
  %h2
    %b Name:
    =@task.name
%p
  %b Completed:
  =@task.completed
%p
  %b Task History:
  -@task.audits.each do |rev|
    %li
      %b= "Version #{rev.id}"
      %p= rev.audited_changes





=link_to 'Edit', edit_task_path(@task)
\|
=link_to 'Back', tasks_path

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>